spring.application.name=Databaseconnection
server.port=9090


spring.datasource.url=jdbc:postgresql://localhost:5432/user
spring.datasource.username=postgres
spring.datasource.password=Mvinod@4284

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
